### ISSUE TITLE
logout never finished

### ISSUE THREAD

**Issue by vinej** [nightwolfz/inferno-starter#1]
I tried it on window10
- Signing out... stay on screen with this error into the console
    Unable to get property 'username' of undefined or null reference
- Login and Register are ok, but when I come back, my last todos are not there
  The database contains all the information, but todos are not shown in the page.
  maybe related to the bad logout 
- need to tell people to launch mongodb (mongod) before 'npm run dev'

Thanks

**Comment by nightwolfz** [comment]
This was made in a bit of a rush :-)

I still need to do the following:
- JWT based authentication instead of sessions, so our the app can be fully isomorphic.
- Fix many small issues that are not apparent at the first glance.
- Maybe use (https://github.com/iwillwen/mindb)[minDB] instead of mongo. Since they both use the same syntax migrating from one to another shouldn't be problem.

Thanks for testing !

**Comment by vinej** [comment]
Token based authentification is better. I used it on react-portal.

I will do more tests.

**Comment by nightwolfz** [comment]
@vinej Thanks! I just pushed some fixes.

There's still work to be done though :)

**Comment by minimok** [comment]
This is nice work! The logout functionality may need looking at. If I manually navigate using '/logout' in the browser's address bar - the result is not what I'd expect. (needs handling) That's the only bug I've found...but this is a lovely piece of work! *am looking at i18n options - i18next looks nice any thoughts?

**Comment by vinej** [comment]
I did some tests on windows7

1) Chrome : Working with the same issue than minimok (I think that the logout must return to a splash screen, not to a empty Todo)

2) Not working on IE11 on register or login
      Unhandled promise rejection Error: TypeError: The object doesn't support property or method« find »

I had this kind of problem in the past with IE. Polyfill is not perfect, sometime you'll have to include your own definition. (find, findIndex, ...)

3) Firefox : Working, but the validators are executed too soon. The fields for the register and the login pages are always surrounded by a red line.

4) Safari : Not working on register or login
     SECURITY_ERR: DOM Exception 18: An attempt was made to break through the security policy of the user agent. ??? I don't know why.

Thanks

**Comment by minimok** [comment]
I hacked in a new server route '/logout' . It updates the db (sets token null), then clears out context and does a res.redirect('/') - this handles the manual navigation ok. I also threw away the Logout stuff in the client and just made the /logout route do: ()=> window.location.href='/logout' - this works fine, and returns the user to the home page as I'd expect.

**Comment by nightwolfz** [comment]
I managed to fix IE11 issues you mentioned by included a few polyfills. 

I didn't want to include the whole of babel-polyfill because it's huge and we only needed a few methods to make IE11 work.

As a goal, I'd like to keep the dependencies to a minimum and lower the bundle size as much as I can.

**Comment by nightwolfz** [comment]
I haven't tried [react-i18next](https://github.com/i18next/react-i18next) yet but it seems to be well maintained and easy to use.

I will work some more on it when I find time.

**Comment by vinej** [comment]
I did re-tests with IE11 on Windows 7

IE : not working. the polyfill error is gone, but I have this error when I click enter to add a todo
    Warning: a promise was rejected with a non-error: [object String](No stack trace)
       From previous event:
       at Anonymous function (eval code:35:9)
       at add (eval code:28:13) 
    Unhandled rejection [text] not provided

It's only a warning, but the todo stays into the field after the enter

Thanks

**Comment by nightwolfz** [comment]
That's a really strange one. 

After some testing, I figured out that if you type some text, blur the input box by clicking somewhere else and then go back and hit enter... it works.

At this point I'm not sure where the problem lies, it could be a bug in Inferno.

**Comment by vinej** [comment]
For the IE error, I also have this error into the **server console**.
- logger:error (node:11108) Warning: a promise was created in a handler but was't returned from it   +7ms

Also, there is a difference between react and inferno
- with inferno:  onchange  event is only dispatch after you blur/defocus the text/textarea input. this is typical DOM behavior (unrelated to Inferno). 
- with react the "onchange" event is called for every key.

Thanks

**Comment by nightwolfz** [comment]
@vinej Ah that makes sense!

I changed onChange to onKeyUp and forms are working again. 
Also added protected routes. The promise warning should be gone too.

I'll have to refactor everything into a nicer structure at some point.
