### ISSUE TITLE
SSR doesn't seem to work out of the box

### ISSUE THREAD

**Issue by pcole** [nightwolfz/inferno-starter#13]
Hi, 

Thanks for making this starter project. I'm using it as a base for my first Inferno project and it is also the first time I use a 'react like' framework so I may be missing something obvious.

Here are my steps: 

- cloned the repo
- `$ npm install`
- `$ npm run dev`

This works fine and I can play around with the app.

Then I set SSR to true in the config file, reload, and get the following error:

`TypeError: Cannot read property 'sort' of undefined`

Which comes from inferno-router. Any ideas?

Many thanks.

**Comment by trueadm** [comment]
Hi @pcole what version of Inferno are you using? @nightwolfz

**Comment by nightwolfz** [comment]
@pcole Thanks for creating an issue. I have found the bug, it should be fixed soon. In the meantime just disable SSR 👍

**Comment by pcole** [comment]
Thanks guys! I'm using it without SSR for now, no worries :-)

**Comment by nightwolfz** [comment]
@pcole Pull the changes and `npm install` ;-)

**Comment by nightwolfz** [comment]
@pcole Pull in the latest changes and `npm install`, it should work now!

**Comment by pcole** [comment]
All working now thanks!
