### ISSUE TITLE
Redundant first render

### ISSUE THREAD

**Issue by standy** [nightwolfz/inferno-starter#15]
Hi, 
I noticed that `Todos` has redundant render. It happens even before `browse` actions starts, cant figure out how to avoid this.
Did some code to demonstrate: https://github.com/standy/inferno-starter/commit/c2c81a8546802853e7725a9ce2413cdd5ca5a0ad

Steps to reproduce:
1. Login, make few todo
2. Switch to About
3. Refresh page
4. Move to Todos

Console shows 3 renders:
1. Empty list, loading: false (should be skipped)
2. Empty list, loading: true
3. Full list, loading: false

PS: Thank you for great tool, really intending to make my next project with this

**Comment by nightwolfz** [comment]
@standy Thanks for the issue, I didn't notice this before. Pull in the latest changes, it should behave better now 👍

**Comment by standy** [comment]
Yeah, that fixed!

But there is another one problem: if no changes in `this.loading` at `browse()` action, render still happens
Expected that client re-render happens only after store changes. Like react-starter-kit do render only after fetch finished.

Demo (same as this repo + log) https://github.com/standy/inferno-starter/commit/5329c44a3ec20e548cfee8959c47146a267741f2
Steps to reproduce the same 
Console shows:
1. Empty list - should be skipped
2. Full list

**Comment by nightwolfz** [comment]
@standy Do you still get the render if you change `console.log('Todos#render', toJS(todos))` to `console.log('Todos#render')` ?

**Comment by standy** [comment]
Yes, still double render

**Comment by nightwolfz** [comment]
@standy According to the mobx documentation, to optimize the already fast rendering and reduce calls to `render` you will have to use a wrapper element.

ex:
```javascript
@connect(['todos'])
class Todos extends Component {

    // When route is loaded (isomorphic)
    static onEnter({ todos, common, params }) {
        common.title = 'Home'
        return todos.browse()
    }

    render({ todos }) {
        console.log('Todos#render')
        return <main>
            <h1>todos</h1>
            <div className="home">
                <TodoAdd/>
                <section className="main">
                    <TodoItemWrapper todos={todos}/>
                </section>
            </div>
        </main>
    }
}

function TodoItemWrapper({ todos }) {
    return <ul className="todo-list">
        {todos.map(item => (
            <TodoItem key={item.text.hashCode()} item={item}/>
        ))}
    </ul>
}
```

**Comment by standy** [comment]
Now empty `todos` on page change. Full list fetched but not rendered.

**Comment by nightwolfz** [comment]
@standy That's odd, it's working fine here with and without server side rendering.

**Comment by nightwolfz** [comment]
@standy  My bad, you need to connect your wrapper too

```javascript
const TodoItemWrapper = connect(props => ( 
    <ul className="todo-list">
        {props.todos.map(item => <TodoItem item={item}/>)}
    </ul>
))
```

**Comment by standy** [comment]
Still getting first render with empty list, but now its for `TodoItemWrapper` 
Fetch too fast on starter project to notice that, so i did demo with delay and more data: https://github.com/standy/inferno-starter/commit/24a688eba2fef9bcac3f50630f539239333d731f
It clearly shows render with initial/old data when you switch About->Browse

In real world app you dont want to render page before you fetch all you need from server, so I suppose that issue with router. It should wait for `onEnter` promises of all components before pushing to history, same as it done in SSR

**Comment by nightwolfz** [comment]
@standy You can render after executing `onEnter` promises like this in `client.js`:

```javascript
// Fetch data on route change
history.listen(location => {
    onEnter(match(routing, location), stores)
})

/**
 * Render our component according to our routes
 */
onEnter(match(routing, window.location), stores).then(() => {
    Inferno.render(<App stores={stores}>
        <Router history={history}>
            {routing}
        </Router>
    </App>, container)
})
```

However this seems to break hot-reloading. The issue is in the router, I will fix it when I get a moment free.

**Comment by sallespro** [comment]
hi, i noticed todos being rendered when one logs out, before finaly routing to login. i wonder this might be the same. Also noticed the hot reload not working.

**Comment by standy** [comment]
@nightwolfz 
Unfortunately it didnt help
Take a look at the gif demo https://hsto.org/files/7b4/851/90f/7b485190f1ff47fbaec81acece77ab16.gif
When pages switches on client side - there is first render with empty data, that i really want to avoid.

I think it could be solved with router's onEnter hook, like in RR3 [Link to API](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#onenternextstate-replace-callback) 
> onEnter(nextState, replace, callback?)
> If callback is listed as a 3rd argument, this hook will run asynchronously, and the transition will block until callback is called.

But not such option in inferno-router

**Comment by nightwolfz** [comment]
@standy There are plans to improve inferno-router, unfortunately it's a super busy period for me but we'll get there eventually. I use inferno-starter on all my projects and it's one of the improvements I've been wanting to add for a while.
