### ISSUE TITLE
Errors when accessing prod

### ISSUE THREAD

**Issue by JohnRSim** [nightwolfz/inferno-starter#18]
Maybe something I did - will try tomorrow with latest updates.

When I run 'npm run prod' I get the following issues:

Uncaught (in promise) TypeError: Cannot read property 'push' of undefined
    at isAuthenticated (bundle.js.download:19880)
    at bundle.js.download:4209

Also socket connection requests keep trying to poll.
http://localhost:2002/sockjs-node/info?t=1484083399582 net::ERR_CONNECTION_REFUSED.
---

In dev if I add a reference to an image/font in the scss they do not load as webpack css conversion is on port 2002 but the site assets are on port 2000. Works fine when pushed to prod or if I put in the full domain/port - maybe there is a webpack setting for this - I will take a look.

**Comment by nightwolfz** [comment]
There was a change with `inferno-router`, I just updated the code to reflect that.

```js
    function isAuthenticated({ props, router }) {
        if (!account.isLoggedIn()) {
            router.replace('/page/login')
        }
    }
```

**Comment by JohnRSim** [comment]
Thanks that fixed all my issues. 
Noticed when I log out the todos page still displays and not redirected to login - but that's a quick fix.
