### ISSUE TITLE
Make into NPM module

### ISSUE THREAD

**Issue by scottburch** [nightwolfz/inferno-starter#19]
I have been enjoying the layout of inferno-starter.  I think it would be good if it was an upgradable module rather than a template.  I don't think it would take long to do, and I could take a couple of days to give it a shot.  Any interest?  Do you see any reason why that would be a bad thing?

I would stay with convention over configuration, which is pretty easy with webpack contexts.

**Comment by nightwolfz** [comment]
@scottburch I had the idea for a while as well, although I'm not sure what could go into a package. Obviously the `core` is a good candidate but there should be an easy way to configure webpack as well.
Another improvement would be to compile server-side es6 code to es5, making so we have two bundles in total. Ex: `build/bundle.client.js` and `build/bundle.server.js`

Do note that this is a starter, it's not a framework :) People have already complained in the past that it tries to do too much. In any case, the npm package should be a separate project, feel free to fork and play around for fame and/or fortune. 👍

**Comment by scottburch** [comment]
@nightwolfz Thanks for your thoughts.  I really appreciate it.  I am well into building something on top of the starter.  And, if I called it  a framework, that was a slip, thanks for the correction. :)

I agree that it should be a separate project.  My thoughts about configuring webpack was to just add another layer like you did with the core and the client/server configs.  There would be a place to extend them further since I already have in the files that you provided.

I'm confused about people complaining that it tries to do too much, but I will keep that in mind.  I have enjoyed working with it so far and have dug into how it works more as I have built on top of it.

I also agree with the server side pre-compiling.  I see that it is using babel-register right now to hook into require.

I think the only built-in feature that I am not using is the hook into mongo.  I had a server setup with services already, so I am just doing service calls, that was easy to do with this starter.  I think the starter was quite flexible and relatively simple to use.  Only took a little digging to figure out how things were being done.

I will be finishing up what I am working on at the moment and then attempt to create an npm package.  Thanks for being kind enough to provide the wonderful base to start with.  I will make sure you get credit.

**Comment by scottburch** [comment]
For those that see this.  I am finally starting on this other project to make a upgradable NPM module.  More to come.

**Comment by dav-is** [comment]
Update on this?

**Comment by scottburch** [comment]
@dav-is I stopped on it.  I got a little way into the conversion, but not completely. I moved the product to another framework so there was no need.  Sorry I did not write before.
