### ISSUE TITLE
Logging In from multiple browsers/devices

### ISSUE THREAD

**Issue by minimok** [nightwolfz/inferno-starter#2]
So I log in from desktop Safari - the server allocates me my token, and everything is good. Now I go to my phone, and log in - so the token is created again and over-written in the db. Back to Safari and refresh the page...and of course I've been logged out. Not a bug - but a business logic issue. Would it be good (after a successful log in) to check for an existing token and re-use it for the 2nd device?

**Comment by nightwolfz** [comment]
Thanks, I didn't think about that, noted ! 

The current implementation is very basic and only one token can be generated per user.

From a security perspective, it's probably better to give both devices a different token with different expiration.
