### ISSUE TITLE
promise error with post.

### ISSUE THREAD

**Issue by JohnRSim** [nightwolfz/inferno-starter#21]
I noticed if I login / logout and then log back in I get this error every so often
SSR Enabled.

Uncaught (in promise) TypeError: Request method 'POST' is unsupported
    at service.js:50
(anonymous) @ service.js:50

Also not sure if this is because of the service workers.
If I login / logout and select browse and goto the root path '/' then I see the todos page.. 
But it I ctrl f5 then it redirects back to login.

**Comment by nightwolfz** [comment]
@JohnRSim Can you try the latest version on master? If it still doesn't work, you can always remove the service worker in `client.js` :)

**Comment by salembaira** [comment]
This is a bug in the service worker, adressed it by switching to the sw-precache-webpack-plugin  #23
