### ISSUE TITLE
webpack resolve alias doesnt work

### ISSUE THREAD

**Issue by salembaira** [nightwolfz/inferno-starter#24]
Hi,

First of all, thank you very much for the awesome work you've done here !

I've been trying for many hours to make resolve alias work in webpack.base.config but couldn't.

I installed a react plugin "material-ui" and tried unsucceffuly to use resolve alias to make webpack point react imports to inferno-compat.

`    resolve: {
        alias: {
            'core': path.join(__dirname, '../'),
            'react': 'inferno-compat',
            'react-dom': 'inferno-compat'
        },
    },`

Here is the error i get :
`Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:470:15)
`

It's worth noting that resolve alias works with all my other projects using webpack

**Comment by nightwolfz** [comment]
Sorry I haven't used inferno-compat before ¯\_(ツ)_/¯
