### ISSUE TITLE
multiple layouts in router

### ISSUE THREAD

**Issue by salembaira** [nightwolfz/inferno-starter#29]
Hi,

I'm trying to build multiple layouts in router but no success so far :

    return (
        <Route component={ Layout }>
            <Route component={ HomeLayout }>
                <Route path="/services" component={ Services }/>
            </Route>
            <Route component={ PlusLayout }>
                <Route path="/blog" component={ Blog }/>
            </Route>
        </Route>
    )
/services render properly but /blog doesnt render the blog component. What's the problem ?

**Comment by nightwolfz** [comment]
@Baira In your routes, first Layout is always matched then HomeLayout is matched, so the PlusLayout never gets matched.

Try the following?

```
return (
    <Route component={ Layout }>
        <Route path="/services" component={ HomeLayout }>
            <Route path="/services" component={ Services }/>
            <Route path="/services/something" component={ ServicesSomething }/>
        </Route>
        <Route path="/blog" component={ PlusLayout }>
            <Route path="/blog" component={ Blog }/>
            <Route path="/blog/something" component={ BlogSomething }/>
        </Route>
    </Route>
)
```

**Comment by salembaira** [comment]
Thank you @nightwolfz . I understand the logic now. Just disappointed that the inferno router documentation doesn't mention this nested routes behavior at all.
