### ISSUE TITLE
Production doesn't serve assets or build directory...

### ISSUE THREAD

**Issue by dav-is** [nightwolfz/inferno-starter#33]
I had to add 2 missing dependencies to the package.json file. Production doesn't serve assets or build directory...

Can you reproduce? Dev seems to work fine

**Comment by nightwolfz** [comment]
Production node.js is not meant to serve the files, you should use another server such as nginx or apache for it.

If you look in `server/server.js`, you will see it's disabled on purpose:

```js
// Serve static files
if (process.env.NODE_ENV !== 'production') {
  const mount = require('koa-mount')
  const serve = require('koa-static')

  for(const [k, v] of Object.entries(config.http.static)) {
    app.use(mount(k, serve(v, {index: false})))
  }
}
```

Remove the `if` check to re-enable.

And in `server/config.js`, you can set which directories to server static files from.

**Comment by dav-is** [comment]
If that’s the case, my mistake I removed the if statement in my PR. My apologies.
