### ISSUE TITLE
Error when logging in to the test app.

### ISSUE THREAD

**Issue by cibelius** [nightwolfz/inferno-starter#4]
Get this error on console:

`inferno-dom.js:337 Uncaught (in promise) DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.`

and not showing todo-list when trying to log into the app. Refreshing page fixes the problem. Not sure if worth fixing but wanted to let you know :)

**Comment by nightwolfz** [comment]
Yeah it's been annoying me as well. It's an edge case issue with the current version of Inferno, it can probably be fixed by slightly changing the logic in the Login component.

It's fixed in inferno 1.0 which will hopefully come out soon :)
https://github.com/trueadm/inferno/issues/323

**Comment by nightwolfz** [comment]
@Keksike You can try the `next` branch, if you're okay with using koa instead of express.
