### ISSUE TITLE
feathers for koa

### ISSUE THREAD

**Issue by joshua1** [nightwolfz/inferno-starter#8]
Hi @nightwolfz 
I would like to swap out koa for feathersjs for the backend. What steps do you recommend i take

**Comment by nightwolfz** [comment]
@joshua1 

I haven't used feathers but from the looks of it, I don't think it will be hard to migrate.

I would start having a clean `client.js` with nothing but just a simple hello world component renderer. Afterwards migrate the middleware (context.js) and render.js

Once you get that first hello world component rendered, the rest shouldn't be hard:

Add routes, migrate authorize.js middleware, decide if you want to use feathers db adapters or mongoose etc

**Comment by nightwolfz** [comment]
You can look at older commits using `express` for inspiration:

https://github.com/nightwolfz/inferno-starter/blob/43ddeb699da546ea9e558da9cef3357122b7f3b1/src/server/middleware/render.js

https://github.com/nightwolfz/inferno-starter/blob/43ddeb699da546ea9e558da9cef3357122b7f3b1/src/server/middleware/context.js

**Comment by joshua1** [comment]
@nightwolfz Thanks a lot, would do
